name: tourconnect
description: "A professional travel mobile application connecting tourists with local guides."
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  google_fonts: ^6.1.0
  animate_do: ^3.3.4
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  supabase_flutter: ^2.5.0
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
